# SITE SETUP
appearance:
  theme: minimal
  color: red
  font_size: s
  custom_css: ["css/custom.css"]

marketing:
  seo:
    site_type: Person
    local_business_type: ''
    org_name: ''
    description: 'Luca Looser is a PhD Candidate in Economics at Universitat Pompeu Fabra working on macro development, economic geography, and family economics.'
  analytics:
    google_analytics: ''
    baidu_tongji: ''
    plausible: ''
    fathom: ''
    pirsch: ''
  verification:
    google: ''
    baidu: ''

header:
  navbar:
    enable: true
    block: 'navbar'
    fixed_to_top: true
    show_search: false
    show_theme_chooser: false
    reading_time: false
    logo:
      text: 'Luca Looser'

footer:
  copyright:
    notice: ''
    license:
      enable: false
      allow_derivatives: false
      share_alike: false
      allow_commercial: false

locale:
  date_format: 'Jan 2, 2006'
  time_format: '3:04 PM'

features:
  math:
    enable: true
  privacy_pack:
    enable: false
  font_size: s
